// Build script: roll up src/client/* into lib/client.js, wrap in __ModuleLoader__.
//
// Mirrors dsh-pictor's pattern: src/client/index.js is the canonical source;
// build.mjs bundles transitive imports (styles, components, pages, api, md)
// into a single browser-ready file. esbuild handles ESM resolution.

import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'lib');

mkdirSync(OUT, { recursive: true });

// Host: roll up src/host/index.ts (→ apply.js + session-store.js + llm.js +
// prompt.js + default-model.js + question-bank.js + shared/schema.js) into
// one lib/index.js. esbuild handles JS+TS, no external (host has zero deps).
await build({
  entryPoints: [join(ROOT, 'src/host/index.ts')],
  outfile: join(OUT, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  logLevel: 'info',
});

// Client: roll up src/client/index.js + its imports into one browser file.
// `react` is left external — only the ModuleLoader factory has access to it.
await build({
  entryPoints: [join(ROOT, 'src/client/index.js')],
  outfile: join(OUT, 'client.bundle.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  external: ['react'],
  logLevel: 'info',
});

const body = readFileSync(join(OUT, 'client.bundle.js'), 'utf8');
const wrapped = `// dsh-ielts-examiner client half (browser).
// Generated by scripts/build.mjs — edit src/client/index.js (and friends) instead.
window.__ModuleLoader__.load({
  id: "dsh-ielts-examiner",
  factory: (require) => {
${body}
return { inject: exports.inject, apply: exports.apply };
  }
});`;
writeFileSync(join(OUT, 'client.js'), wrapped);

console.log('[build] lib/index.js + lib/client.js written');
