import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'lib');

mkdirSync(OUT, { recursive: true });

// Host: roll up src/host/index.ts (→ apply.js + session-store.js + llm.js +
// prompt.js + default-model.js + question-bank.js + shared/schema.js) into
// one lib/index.js. esbuild handles JS+TS, no external (host has zero deps).
await build({
  entryPoints: [join(ROOT, 'src/host/index.ts')],
  outfile: join(OUT, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  logLevel: 'info',
});

// Client: concatenate src/client/*.js into one file, then wrap in the
// __ModuleLoader__ envelope. No esbuild bundling — pictor's pattern.
// The factory body sees top-level `const inject` and `function apply`
// directly; React comes from the `require` provided by ModuleLoader.

import { readdirSync } from 'node:fs';
const CLIENT_DIR = join(ROOT, 'src/client');
const clientFiles = readdirSync(CLIENT_DIR)
  .filter((f) => f.endsWith('.js'))
  .sort();
const banner = `// dsh-ielts-examiner client half (browser).
// Generated by scripts/build.mjs — edit src/client/*.js instead.
// Concatenated files: ${clientFiles.join(', ')}.
window.__ModuleLoader__.load({
  id: "dsh-ielts-examiner",
  factory: (require) => {
`;
const footer = `
return { inject, apply };
  }
});
`;
const body = clientFiles
  .map((f) => {
    let src = readFileSync(join(CLIENT_DIR, f), 'utf8');
    // Strip ESM `export` keywords so all top-level declarations live in the
    // ModuleLoader factory's closure scope (pictor pattern). Handle:
    //   export function name(...)  →  function name(...)
    //   export const name = ...   →  const name = ...
    //   export default X          →  const __default_X = X  (rarely used)
    src = src.replace(/^export\s+(async\s+)?function\s+/gm, '$1function ');
    src = src.replace(/^export\s+const\s+/gm, 'const ');
    src = src.replace(/^export\s+let\s+/gm, 'let ');
    src = src.replace(/^export\s+default\s+/gm, 'const __default__ = ');
    // Strip `import` statements — all imports must be listed in the build
    // (pictor has everything in one file; we keep multi-file source for
    // organization but flatten at build time).
    src = src.replace(/^import\s+.*?from\s+['"][^'"]+['"];?\s*$/gm, '');
    return `// ── src/client/${f} ─────────────────────────────────────────────\n${src}`;
  })
  .join('\n\n');
writeFileSync(join(OUT, 'client.js'), banner + body + '\n' + footer);

// Remove the unused client.bundle.js from earlier IIFE builds (cleanup).
try { rmSync(join(OUT, 'client.bundle.js')); } catch {}

console.log('[build] lib/index.js + lib/client.js written');
