// Build script: bundle host TS entries → lib/*.js (esbuild, ESM),
// wrap client/index.js into the __ModuleLoader__ factory envelope.
//
// Mirrors dsh-pictor/scripts/build.mjs shape (host bundle, then client wrap).

import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'lib');

mkdirSync(OUT, { recursive: true });

// Host: bundle each entry to lib/. esbuild handles TS+ESM, no external.
await build({
  entryPoints: [
    join(ROOT, 'src/host/index.ts'),
  ],
  outdir: OUT,
  bundle: false,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  logLevel: 'info',
});

// Client: wrap src/client/index.js in the __ModuleLoader__ envelope.
// esbuild bundles all transitive imports from src/client/* into a single file
// so we have one canonical client entry.
await build({
  entryPoints: [join(ROOT, 'src/client/index.js')],
  outfile: join(OUT, 'client.bundle.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  loader: { '.js': 'jsx', '.css': 'text' },
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  logLevel: 'info',
});

const body = readFileSync(join(OUT, 'client.bundle.js'), 'utf8');
const wrapped = `// dsh-ielts-examiner client half (browser).
// Generated by scripts/build.mjs — edit src/client/index.js instead.
window.__ModuleLoader__.load({
  id: "dsh-ielts-examiner",
  factory: (require) => {
${body}
return { inject: exports.inject, apply: exports.apply };
  }
});`;
writeFileSync(join(OUT, 'client.js'), wrapped);

// Remove the intermediate bundle (kept inside client.js now).
// (No rm — caller can gitignore lib/ freely.)

console.log('[build] lib/index.js + lib/client.js written');
